// <auto-generated />
using System;
using CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Comfortable passenger cars",
                            Name = "Sedan"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sport utility vehicles",
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Compact practical cars",
                            Name = "Hatchback"
                        });
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DriverLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DriverLicenseNumber")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DriverLicenseNumber = "DL100001",
                            Email = "ahmed.hassan@example.com",
                            FullName = "Ahmed Hassan",
                            Phone = "01010000001"
                        },
                        new
                        {
                            Id = 2,
                            DriverLicenseNumber = "DL100002",
                            Email = "mona.adel@example.com",
                            FullName = "Mona Adel",
                            Phone = "01010000002"
                        },
                        new
                        {
                            Id = 3,
                            DriverLicenseNumber = "DL100003",
                            Email = "omar.khaled@example.com",
                            FullName = "Omar Khaled",
                            Phone = "01010000003"
                        });
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Models.CustomerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("CustomerProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Nile St. ",
                            City = " Cairo",
                            CustomerId = 1,
                            DateOfBirth = new DateTime(1992, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Egyptian"
                        },
                        new
                        {
                            Id = 2,
                            Address = "34 Tahrir St. ",
                            City = " Cairo",
                            CustomerId = 2,
                            DateOfBirth = new DateTime(1990, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Egyptian"
                        },
                        new
                        {
                            Id = 3,
                            Address = "18 El Nasr  St. ",
                            City = " Cairo",
                            CustomerId = 3,
                            DateOfBirth = new DateTime(1995, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Egyptian"
                        });
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "mostafa.nabil@autodrive.com",
                            FullName = "Mostafa Nabil",
                            HireDate = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01010000004",
                            Position = "Sales Manager"
                        },
                        new
                        {
                            Id = 2,
                            Email = "aya.emad@autodrive.com",
                            FullName = "Aya Emad",
                            HireDate = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01010000005",
                            Position = "Sales Consultant"
                        },
                        new
                        {
                            Id = 3,
                            Email = "hassan.ali@autodrive.com",
                            FullName = " Hassan Ali",
                            HireDate = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01010000006",
                            Position = "Sales Consultant"
                        });
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            EmployeeId = 1,
                            Notes = "Completed sale",
                            PaymentMethod = "Bank Transfer",
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2003),
                            SalePrice = 1750000m,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            EmployeeId = 2,
                            Notes = "Completed sale",
                            PaymentMethod = "Bank Transfer",
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1996),
                            SalePrice = 1850000m,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            EmployeeId = 3,
                            Notes = "Completed sale",
                            PaymentMethod = " Cash",
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1988),
                            SalePrice = 1950000m,
                            VehicleId = 3
                        });
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FuelType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Available");

                    b.Property<string>("Transmission")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Color = "White",
                            FuelType = "Petrol",
                            Make = "Toyota",
                            Mileage = 12000,
                            Model = "Corolla",
                            Price = 650000m,
                            Status = "Available",
                            Transmission = "Automatic",
                            VIN = "1HGCM82633A123456",
                            Year = 2024
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Color = "Black",
                            FuelType = "Petrol",
                            Make = "Hyundai",
                            Mileage = 18000,
                            Model = "Elantra",
                            Price = 590000m,
                            Status = "Available",
                            Transmission = "Automatic",
                            VIN = "1HGCM82633A654321",
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Color = "Gray",
                            FuelType = "Petrol",
                            Make = "Kia",
                            Mileage = 9000,
                            Model = "Sportag",
                            Price = 980000m,
                            Status = "Available",
                            Transmission = "Automatic",
                            VIN = "1HGCM82633A987654",
                            Year = 2024
                        });
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Models.CustomerProfile", b =>
                {
                    b.HasOne("CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Models.Customer", "Customer")
                        .WithOne("CustomerProfile")
                        .HasForeignKey("CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Models.CustomerProfile", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Models.Sale", b =>
                {
                    b.HasOne("CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Models.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Models.Employee", "Employee")
                        .WithMany("Sales")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Models.Vehicle", "Vehicle")
                        .WithOne("Sale")
                        .HasForeignKey("CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Models.Sale", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Models.Vehicle", b =>
                {
                    b.HasOne("CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Models.Category", "Category")
                        .WithMany("Vehicles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Models.Category", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Models.Customer", b =>
                {
                    b.Navigation("CustomerProfile");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Models.Employee", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANAGEMENT_SYSTEM.Models.Vehicle", b =>
                {
                    b.Navigation("Sale");
                });
#pragma warning restore 612, 618
        }
    }
}
